/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function initLogger(level: string): void
export declare class NativeEnkiAgent {
  constructor(name?: string | undefined | null, systemPromptPreamble?: string | undefined | null, model?: string | undefined | null, maxIterations?: number | undefined | null, workspaceHome?: string | undefined | null)
  static withTools(name: string | undefined | null, systemPromptPreamble: string | undefined | null, model: string | undefined | null, maxIterations: number | undefined | null, workspaceHome: string | undefined | null, tools: Array<object>, toolHandler?: SharedToolCallback | undefined | null): NativeEnkiAgent
  static withMemory(name: string | undefined | null, systemPromptPreamble: string | undefined | null, model: string | undefined | null, maxIterations: number | undefined | null, workspaceHome: string | undefined | null, memories: Array<JsMemoryModule>, recordHandler: RecordCallback, recallHandler: RecallCallback, flushHandler: SessionCallback, consolidateHandler: SessionCallback): NativeEnkiAgent
  static withToolsAndMemory(name: string | undefined | null, systemPromptPreamble: string | undefined | null, model: string | undefined | null, maxIterations: number | undefined | null, workspaceHome: string | undefined | null, tools: Array<object>, toolHandler: SharedToolCallback | undefined | null, memories: Array<JsMemoryModule>, recordHandler: RecordCallback, recallHandler: RecallCallback, flushHandler: SessionCallback, consolidateHandler: SessionCallback): NativeEnkiAgent
  run(sessionId: string, userMessage: string): Promise<unknown>
  runWithTrace(sessionId: string, userMessage: string): Promise<JsAgentRunResult>
}

export declare class NativeMultiAgentRuntime {
  constructor(members: Array<JsMultiAgentMember>, workspaceHome?: string | undefined | null)
  process(agentId: string, sessionId: string, userMessage: string): Promise<unknown>
  processWithTrace(agentId: string, sessionId: string, userMessage: string): Promise<JsAgentRunResult>
  registry(): Promise<unknown>
  discover(capability?: string | undefined | null, status?: JsAgentStatus | undefined | null): Promise<unknown>
}

export interface JsAgentCard {
  agentId: string
  name: string
  description: string
  capabilities: Array<string>
  status: JsAgentStatus
}

export declare const enum JsAgentStatus {
  Online = 'Online',
  Busy = 'Busy',
  Offline = 'Offline'
}

export interface JsMemoryEntry {
  key: string
  content: string
  kind: JsMemoryKind
  relevance: number
  timestampNs: string
}

export interface JsExecutionStep {
  index: number
  phase: string
  kind: string
  detail: string
}

export interface JsAgentRunResult {
  output: string
  steps: Array<JsExecutionStep>
}

export declare const enum JsMemoryKind {
  RecentMessage = 'RecentMessage',
  Summary = 'Summary',
  Entity = 'Entity',
  Preference = 'Preference'
}

export interface JsMemoryModule {
  name: string
}

export interface JsMultiAgentMember {
  agentId: string
  name: string
  systemPromptPreamble?: string
  model?: string
  maxIterations?: number
  capabilities: Array<string>
}
